[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "IsaacLab"
readme  = "README.md"

title = "RMA Isaac Lab Extension"
author = "Mason Russell"
maintainer = "Mason Russell"
maintainer_email = "mrus91@utexas.edu"
description="RMA Extension for Isaac Lab"
repository = "https://github.com/mrussell9/IsaacLab"
keywords = ["extension", "IsaacLab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "isaaclab.rma"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"